from email.mime import image
import os

image_folders = ["digital-art", "minimal", "pixel-art"]
image_folders.sort()
print(image_folders)

pre = """
# just a bunch of wallpapers.....
**NOTE: I do not take credit for any of the wallpapers in this repository. I made none. Some may be generated by AI**
"""

post = """
</p>
"""
with open("./README.md", "w") as f:
    f.write(pre)

def image_embed(title,folder,img):
    return f"""<img src="./{folder}/{img}" title="{title}"><br>\n"""

with open("./README.md", "a") as readme:
    for folder in image_folders:
        readme.write("\n\n## " + folder + "\n")
        readme.write("<details><summary></summary>\n")
        for file in os.listdir(folder):
            if file.endswith(".jpg") or file.endswith(".png") or file.endswith(".gif") or file.endswith(".webp") or file.endswith(".webm"):
                readme.write(
                    image_embed(file[:-4], folder, file)
                )
        readme.write("</details>\n")
    readme.write(post)
